import './globals.css'
import "@/app/scss/index.scss"
import type { Metadata } from 'next'
import Navbar from './sections/Navbar'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kazim Hussain',
  description: 'Generated by Kazim Hussain',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar/>
        </div>
        {children}</body>
    </html>
  )
}
